Testnet address checking
crossroadlabs/node-cardano-wallet pull request #1
Opened 2019-08-21 13:57 UTC by rooooooooob

As tests of `yoroi-mobile` use this module instead of `react-native-cardano`, we needed to update this module as well to support testnet address generation and checking. The previous version was 

The API should remain consistent as the protocol magic is optional, and when not passed in, while stored in the JSON passed to `js-cardano-wasm`, will be considered as `None` and thus default to mainnet addresses.

**NOTE**: this dependency points to my own fork of `js-cardano-wasm` - once that gets merged, this PR will need to get updated to point to the official IOHK `js-cardano-wasm` dependency.

2019-08-23 12:14 UTC, rooooooooob commented
The js-cardano-wasm PR was merged into IOHK's repo. The dependency has been updated and finalized here.

2019-08-29 18:03 UTC, nicarq requested changes
can you bump up the version in the package.json 🙏

2019-08-29 18:20 UTC, rooooooooob commented
Version bumped, but just minor since the API is not broken. It remains an entirely optional parameter as explained in the description.

2019-08-29 18:34 UTC, nicarq commented
@rooooooooob you sure about that? I don’t see default parameters

2019-08-29 18:41 UTC, rooooooooob commented
I believe @v-almonacid  tested it already. It's javascript as well, so the undefined/whatever values get converted into `None` when it calls the rust wasm code, which then treats it as the same as if the parameter was not in the json when it deserializes the struct. There is then logic in `js-cardano-wasm` to provide the mainnet protocol magic in its place.

2019-08-29 18:45 UTC, merged